//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH
    {
        public int ID { get; set; }
        public string BATCH_STATE { get; set; }
        public string BATCH_RESULT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE_UTC { get; set; }
    }
}
