//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_STEP
    {
        public int ID { get; set; }
        public int BATCH_ID { get; set; }
        public string CHANGE_ACTION { get; set; }
        public Nullable<System.Guid> DATA_SOURCE_TYPE_GUID { get; set; }
        public Nullable<int> DATA_SOURCE_ID { get; set; }
        public string MODIFIED_OBJECT_NAME { get; set; }
        public string FILEPATH { get; set; }
        public string COMMENT { get; set; }
        public string STEP_STATE { get; set; }
        public string STEP_RESULT { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<int> MODIFIED_COUNT { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE_UTC { get; set; }
    }
}
