//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITWISE_DICTIONARY_VALID_VALUES
    {
        public int ID { get; set; }
        public string BITWISE_GROUP { get; set; }
        public string BITWISE_KEY_LIST { get; set; }
        public short BITWISE_VALUE { get; set; }
        public System.DateTime CREATE_DATE_UTC { get; set; }
        public System.DateTime MODIFIED_DATE_UTC { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
