//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_SOURCE_FIELD
    {
        public string CONFIG_COMMON_NAME { get; set; }
        public string DATA_SOURCE_NAME { get; set; }
        public string SOURCE_COLUMN_NAME { get; set; }
        public string SOURCE_COLUMN_DATA_TYPE { get; set; }
        public string RAW_VIEW_COLUMN_NAME { get; set; }
        public string RAW_VIEW_COLUMN_DATA_TYPE { get; set; }
        public bool IS_DIM_HASH { get; set; }
        public bool IS_IDENTITY { get; set; }
        public string DERIVED_CONFIGURATION { get; set; }
        public string COLUMN_NAME { get; set; }
        public string DATA_SOURCE_FIELD_FEATURE { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
        public virtual DATA_SOURCE DATA_SOURCE { get; set; }
    }
}
