//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DIM
    {
        public DIM()
        {
            this.DIM_FIELD = new HashSet<DIM_FIELD>();
        }
    
        public string CONFIG_COMMON_NAME { get; set; }
        public System.Guid DIM_TYPE_GUID { get; set; }        
        public string DIM_COMMON_NAME { get; set; }
        public string DIM_TABLE_SCHEMA { get; set; }
        public string DIM_TABLE_NAME { get; set; }
        public string DIM_TABLE_CLEAN_SCHEMA { get; set; }
        public string DIM_TABLE_CLEAN_NAME { get; set; }
        public string DIM_LOAD_PROC_SCHEMA_RAW { get; set; }
        public string DIM_LOAD_PROC_NAME_RAW { get; set; }
        public string DIM_PROC_UI_CLEAN_SCHEMA { get; set; }
        public string DIM_PROC_UI_CLEAN_NAME { get; set; }
        public string DIM_LOAD_PROC_CLEAN_SCHEMA { get; set; }
        public string DIM_LOAD_PROC_CLEAN_NAME { get; set; }
        public string DIM_VIEW_RAW_SCHEMA { get; set; }
        public string DIM_VIEW_RAW_NAME { get; set; }
        public string DIM_VIEW_CLEAN_SCHEMA { get; set; }
        public string DIM_VIEW_CLEAN_NAME { get; set; }
        public string DIM_PROC_RAW_TABLE_CLEAN_ID_SCHEMA { get; set; }
        public string DIM_PROC_RAW_TABLE_CLEAN_ID_NAME { get; set; }
        public string DIM_VIEW_WHITELIST_SCHEMA { get; set; }
        public string DIM_VIEW_WHITELIST_NAME { get; set; }
        public string DIM_FEATURE { get; set; }
        public string DIM_TAXONOMY_PROC_SCHEMA { get; set; }
        public string DIM_TAXONOMY_PROC_NAME { get; set; }
        public string DIM_LOAD_PRE_PROC_SPROC_SCHEMA { get; set; }
        public string DIM_LOAD_PRE_PROC_SPROC_NAME { get; set; }
        public string DIM_LOAD_POST_PROC_SCHEMA { get; set; }
        public string DIM_LOAD_POST_PROC_NAME { get; set; }
        public string DIM_LOAD_PRE_PROC_CLEAN_SCHEMA { get; set; }
        public string DIM_LOAD_PRE_PROC_CLEAN_NAME { get; set; }
        public string DIM_LOAD_POST_PROC_CLEAN_SCHEMA { get; set; }
        public string DIM_LOAD_POST_PROC_CLEAN_NAME { get; set; }
        public bool IS_STATIC { get; set; }
        public bool IS_AUTO_GENERATED { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
        public virtual DIM_TYPE DIM_TYPE { get; set; }
        public virtual ICollection<DIM_FIELD> DIM_FIELD { get; set; }
        
    }
}
