//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_DATE
    {
        public short DATE_ID { get; set; }
        public int DATE_ID_LONG { get; set; }
        public System.DateTime DATE_SHORT { get; set; }
        public Nullable<System.DateTime> DATE_MONTH { get; set; }
        public Nullable<System.DateTime> DATE_WEEKEND_SAT { get; set; }
        public Nullable<System.DateTime> DATE_WEEKEND_SUN { get; set; }
        public Nullable<System.DateTime> DATE_QUARTER { get; set; }
        public Nullable<byte> DATE_WEEK { get; set; }
        public Nullable<System.DateTime> DATE_YEAR_FORMATTED { get; set; }
        public Nullable<short> DATE_YEAR { get; set; }
        public Nullable<short> DATE_DAY { get; set; }
        public Nullable<System.DateTime> FISCAL_MONTH { get; set; }
        public Nullable<System.DateTime> FISCAL_YEAR { get; set; }
        public Nullable<System.DateTime> FISCAL_QUARTER { get; set; }
        public Nullable<System.DateTime> FISCAL_WEEK { get; set; }
        public Nullable<byte> DATE_MONTH_DAY { get; set; }
        public string DATE_WEEKDAY_NAME { get; set; }
        public Nullable<byte> BROADCAST_MEDIA_WEEK { get; set; }
        public Nullable<byte> BROADCAST_MEDIA_MONTH { get; set; }
        public string BROADCAST_MEDIA_MONTH_NAME { get; set; }
        public Nullable<byte> BROADCAST_MEDIA_QUARTER { get; set; }
        public Nullable<short> BROADCAST_MEDIA_YEAR { get; set; }
    }
}
