//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPTION
    {
        public int EXCEPTION_ID { get; set; }
        public Nullable<int> EXCEPTION_ERROR_NUMBER { get; set; }
        public Nullable<byte> EXCEPTION_ERROR_SEVERITY { get; set; }
        public Nullable<byte> EXCEPTION_ERROR_STATE { get; set; }
        public string EXCEPTION_ERROR_PROCEDURE { get; set; }
        public Nullable<int> EXCEPTION_ERROR_LINE { get; set; }
        public string EXCEPTION_ERROR_MESSAGE { get; set; }
        public Nullable<System.DateTime> EXCEPTION_DATE_UTC { get; set; }
    }
}
