//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDX
    {
        public string CONFIG_COMMON_NAME { get; set; }
        public byte INDX_ORDER { get; set; }
        public string INDX_NAME { get; set; }
        public string TABLE_SCHEMA { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string INDX_FEATURE { get; set; }
        public byte ORDINAL_POSITION { get; set; }
        public bool IS_INCLUDED { get; set; }
        public string INDX_WHERE_CLAUSE { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
    }
}
