//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class METRIC_TYPE
    {
        public System.Guid METRIC_TYPE_GUID { get; set; }
        public string METRIC_TYPE_NAME { get; set; }
        public string METRIC_DATA_TYPE { get; set; }
        public string METRIC_CALCULATION { get; set; }
        public string METRIC_ROLLUP { get; set; }
        public string METRIC_PRORATE { get; set; }
        public Nullable<bool> IS_INTERNAL_AUDIT { get; set; }
        public System.DateTime CREATE_DATE_UTC { get; set; }
        public System.DateTime MODIFIED_DATE_UTC { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
