//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class METRIC
    {
        public string CONFIG_COMMON_NAME { get; set; }
        public System.Guid METRIC_TYPE_GUID { get; set; }
        public string METRIC_NAME { get; set; }
        public string METRIC_OVERRIDE_DATA_TYPE { get; set; }
        public string METRIC_OVERRIDE_CALCULATION { get; set; }
        public string METRIC_OVERRIDE_ROLLUP { get; set; }
        public string METRIC_OVERRIDE_PRORATE { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
    }
}
