//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFIED_TABLE
    {
        public int ID { get; set; }
        public string MODIFIED_OBJECT_NAME { get; set; }
        public string CHANGE_ACTION { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE_UTC { get; set; }
        public Nullable<int> MODIFIED_COUNT { get; set; }
        public string EXECUTING_OBJECT_NAME { get; set; }
    }
}
