//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_BROKER_HISTORY
    {
        public int ID { get; set; }
        public string MESSAGE_BODY { get; set; }
        public string MESSAGE_TYPE_NAME { get; set; }
        public bool IS_RECEIVED { get; set; }
        public bool IS_SENT { get; set; }
        public System.DateTime CREATED_DATE_UTC { get; set; }
    }
}
