//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMMARY
    {
        public string CONFIG_COMMON_NAME { get; set; }
        public string SUMMARY_COMMON_NAME { get; set; }
        public string FACT_COMMON_NAME { get; set; }
        public string SUMMARY_TABLE_SCHEMA { get; set; }
        public string SUMMARY_TABLE_NAME { get; set; }
        public string SUMMARY_LOAD_PROC_SCHEAMA { get; set; }
        public string SUMMARY_LOAD_PROC_NAME { get; set; }
    
        public virtual CONFIG CONFIG { get; set; }
        public virtual FACT FACT { get; set; }
    }
}
