//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CHANGE
    {
        public int ID { get; set; }
        public string TABLE_SCHEMA { get; set; }
        public string TABLE_NAME { get; set; }
        public string DATA_CHANGE_PRE { get; set; }
        public string DATA_CHANGE_POST { get; set; }
        public System.DateTime CREATED_DATE_UTC { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
